export const heroStates = new Map([
	['stay', {
		'action': 'stay',
    'imageSize': [65, 95],
    'spriteSize': [125, 185],
    'firstSpritePosition': [0, 0],
    'framesAmount': 7,	
    'animationDelay': 2000,
    'repeat': true,
	}],
  ['run', {
    'action': 'run',
    'imageSize': [75, 95],
    'spriteSize': [145, 185],
    'firstSpritePosition': [0, 185],
    'framesAmount': 14,	
    'animationDelay': 0,
    'repeat': true,
  }],
  ['aim', {
    'action': 'aim',
    'imageSize': [65, 95],
    'spriteSize': [130, 185],
    'firstSpritePosition': [0, 370],
    'framesAmount': 12,	
    'animationDelay': 0,
    'repeat': true,
  }],
  ['hit', {
    'action': 'hit',
    'imageSize': [95, 95],
    'spriteSize': [185, 185],
    'firstSpritePosition': [0, 555],
    'framesAmount': 8,	
    'animationDelay': 0,
    'repeat': false,
  }],
  ['miss', {
    'action': 'miss',
    'imageSize': [95, 95],
    'spriteSize': [185, 185],
    'firstSpritePosition': [0, 740],
    'framesAmount': 13,	
    'animationDelay': 0,
    'repeat': false,
  }],
  ['take', {
    'action': 'take',
    'imageSize': [85, 95],
    'spriteSize': [170, 185],
    'firstSpritePosition': [0, 925],
    'framesAmount': 9,	
    'animationDelay': 0,
    'repeat': false,
  }],
  ['boom', {
    'action': 'boom',
    'imageSize': [95, 95],
    'spriteSize': [190, 190],
    'firstSpritePosition': [0, 1110],
    'framesAmount': 13,	
    'animationDelay': 0,
    'repeat': false,
  }],
]);

