export { spells, castSpell }

const spells = new Map([
  ['Взрывной удар', {
    'id': 0,
    'name': 'Взрывной удар',
    'heal': false,
    'url': 'images/breath.png',
    'audio': 'audio/explosion.ogg',
    'imageSize': [120, 120],
    'spriteSize': [115, 115],
    'firstSpritePosition': [0, 115],
    'framesAmount': 5,	
    'speed': 15,
    'animationDelay': 0,
    'repeat': true,
  }], 
  ['Удар молнии', {
    'id': 1,
    'name': 'Удар молнии',
    'heal': false,
    'url': 'images/lightning.png',
    'audio': 'audio/thunder.ogg',
    'imageSize': [130, 250],
    'spriteSize': [130, 250],
    'firstSpritePosition': [0, 0],
    'framesAmount': 8,	
    'speed': 10,
    'animationDelay': 0,
    'repeat': true,
  }],
  ['Божественный удар', {
    'id': 2,
    'name': 'Божественный удар',
    'heal': true,
    'url': 'images/heal.png',
    'audio': 'audio/applause.ogg',
    'imageSize': [120, 120],
    'spriteSize': [60, 60],
    'firstSpritePosition': [0, 0],
    'framesAmount': 5,	
    'speed': 10,
    'animationDelay': 0,
    'repeat': true,
  }]
])

const castSpell = new Map([
  ['aim', {
    'url': 'images/castSpell.png',
    'imageSize': [65, 65],
    'spriteSize': [135, 135],
    'firstSpritePosition': [0, 0],
    'framesAmount': 5,	
    'speed': 10,
    'animationDelay': 0,
    'repeat': true,
  }], 
  ['success', {
    'url': 'images/castSpell.png',
    'imageSize': [65, 65],
    'spriteSize': [135, 135],
    'firstSpritePosition': [0, 135],
    'framesAmount': 5,	
    'speed': 10,
    'animationDelay': 0,
    'repeat': true,
  }], 
  ['failure', {
    'url': 'images/castSpell.png',
    'imageSize': [65, 65],
    'spriteSize': [135, 135],
    'firstSpritePosition': [0, 270],
    'framesAmount': 5,	
    'speed': 10,
    'animationDelay': 0,
    'repeat': true,
  }], 
  ['hit', {
    'url': 'images/castSpell.png',
    'imageSize': [270, 270],
    'spriteSize': [135, 135],
    'firstSpritePosition': [0, 405],
    'framesAmount': 5,	
    'speed': 6,
    'animationDelay': 100,
    'repeat': true,
  }], 
]);